### ISSUE TITLE
Depreciate in favor of https://federalist-docs.18f.gov/?

### ISSUE THREAD

**Issue by wslack** [18F/federalist-content-guide#6]
I think https://federalist-docs.18f.gov/ (specifically https://federalist-docs.18f.gov/pages/content-guide/) has the content that was on this repo. Should this repo be closed?

**Comment by jeremiak** [comment]
@wslack I think it should be. We have been centralizing all of our documentation at the `federalist-docs.18f.gov`.

**Comment by wslack** [comment]
Done
